// Code generated by the local DBGEN tool. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import models "github.com/ArnaudLasnier/pingpong/internal/tournamentdatabase/models"

type (
	TournamentStatus = models.TournamentStatus
)

func allTournamentStatus() []TournamentStatus {
	return models.AllTournamentStatus()
}
