// Code generated by the local DBGEN tool. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

type TournamentStatus string

// Enum values for TournamentStatus
const (
	TournamentStatusDraft   TournamentStatus = "draft"
	TournamentStatusStarted TournamentStatus = "started"
	TournamentStatusEnded   TournamentStatus = "ended"
)

func AllTournamentStatus() []TournamentStatus {
	return []TournamentStatus{
		TournamentStatusDraft,
		TournamentStatusStarted,
		TournamentStatusEnded,
	}
}
